"""Add onboarding fields

Revision ID: 24cd36274841
Revises: 14705ee4998e
Create Date: 2026-04-05 13:12:19.620634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24cd36274841"
down_revision: Union[str, None] = "14705ee4998e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vault_files")
    op.add_column(
        "labs", sa.Column("registration_number", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "labs", sa.Column("lab_category", sa.String(length=100), nullable=True)
    )
    op.add_column("labs", sa.Column("state", sa.String(length=100), nullable=True))
    op.add_column("labs", sa.Column("pincode", sa.String(length=10), nullable=True))
    op.add_column("labs", sa.Column("branches", sa.String(length=20), nullable=True))
    op.add_column(
        "labs", sa.Column("pathologist_name", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "labs", sa.Column("pathologist_reg_no", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "labs", sa.Column("nabl_certificate_url", sa.String(length=500), nullable=True)
    )
    op.add_column("labs", sa.Column("is_certified", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_users_pan_card"), "users", ["pan_card"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_pan_card"), table_name="users")
    op.drop_column("labs", "is_certified")
    op.drop_column("labs", "nabl_certificate_url")
    op.drop_column("labs", "pathologist_reg_no")
    op.drop_column("labs", "pathologist_name")
    op.drop_column("labs", "branches")
    op.drop_column("labs", "pincode")
    op.drop_column("labs", "state")
    op.drop_column("labs", "lab_category")
    op.drop_column("labs", "registration_number")
    op.create_table(
        "vault_files",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("cloud_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "cloud_path", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column("file_size_bytes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "file_size_human", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "uploaded_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="vault_files_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="vault_files_pkey"),
    )
    # ### end Alembic commands ###
