"""Sync models with database

Revision ID: 2a37937a8f16
Revises: 002_update_report_model
Create Date: 2026-04-03 11:18:46.610621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2a37937a8f16'
down_revision: Union[str, None] = '002_update_report_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_tickets')
    op.add_column('bookings', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('bookings', sa.Column('promo_code', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('discount_amount', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('cancel_reason', sa.Text(), nullable=True))
    op.drop_column('bookings', 'status')
    op.drop_column('bookings', 'type')
    op.add_column('bookings', sa.Column('type', sa.Enum('home_collection', 'lab_visit', name='bookingtype'), nullable=False))
    op.add_column('bookings', sa.Column('status', sa.Enum('pending', 'confirmed', 'assigned', 'on_the_way', 'arrived', 'sample_collected', 'report_ready', 'completed', 'cancelled', name='bookingstatus'), server_default='pending', nullable=True))
    op.add_column('lab_tests', sa.Column('mrp', sa.Integer(), nullable=False))
    op.add_column('lab_tests', sa.Column('turnaround_hours', sa.Integer(), nullable=False))
    op.add_column('lab_tests', sa.Column('home_collection', sa.Boolean(), nullable=True))
    op.alter_column('lab_tests', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_column('lab_tests', 'preparation')
    op.drop_column('lab_tests', 'discount_price')
    op.drop_column('lab_tests', 'description')
    op.add_column('labs', sa.Column('slug', sa.String(length=100), nullable=False))
    op.add_column('labs', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('labs', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('labs', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('labs', sa.Column('is_nabl', sa.Boolean(), nullable=True))
    op.add_column('labs', sa.Column('is_iso', sa.Boolean(), nullable=True))
    op.add_column('labs', sa.Column('home_collection', sa.Boolean(), nullable=True))
    op.add_column('labs', sa.Column('plan', sa.Enum('starter', 'basic', 'advanced', 'premium', name='subscriptionplan'), nullable=True))
    op.add_column('labs', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.add_column('labs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('labs', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('labs', 'city',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('labs', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('labs', 'lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint('labs_license_number_key', 'labs', type_='unique')
    op.create_index(op.f('ix_labs_city'), 'labs', ['city'], unique=False)
    op.create_index(op.f('ix_labs_slug'), 'labs', ['slug'], unique=True)
    op.drop_constraint('labs_owner_id_fkey', 'labs', type_='foreignkey')
    op.drop_column('labs', 'license_number')
    op.drop_column('labs', 'platform_commission_pct')
    op.drop_column('labs', 'sample_collection_fee')
    op.drop_column('labs', 'owner_id')
    op.drop_column('labs', 'created_at')
    op.drop_constraint('reports_booking_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'bookings', ['booking_id'], ['id'])
    op.add_column('technicians', sa.Column('lab_id', sa.UUID(), nullable=True))
    op.add_column('technicians', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('technicians', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('technicians', sa.Column('vehicle', sa.String(length=50), nullable=True))
    op.add_column('technicians', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('technicians', sa.Column('shift', sa.Enum('morning', 'evening', 'full_day', name='shifttype'), nullable=False))
    op.add_column('technicians', sa.Column('status', sa.Enum('on_duty', 'idle', 'off_duty', 'on_break', name='technicianstatus'), nullable=True))
    op.add_column('technicians', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('technicians', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'technicians', ['phone'])
    op.create_foreign_key(None, 'technicians', 'labs', ['lab_id'], ['id'])
    op.drop_column('technicians', 'is_available')
    op.drop_column('technicians', 'vehicle_type')
    op.drop_column('technicians', 'city')
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lab_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('technician_id', sa.UUID(), nullable=True))
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_foreign_key(None, 'users', 'labs', ['lab_id'], ['id'])
    op.create_foreign_key(None, 'users', 'technicians', ['technician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    op.drop_column('users', 'technician_id')
    op.drop_column('users', 'lab_id')
    op.drop_column('users', 'city')
    op.add_column('technicians', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('technicians', sa.Column('vehicle_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('technicians', sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_constraint(None, 'technicians', type_='unique')
    op.drop_column('technicians', 'is_active')
    op.drop_column('technicians', 'rating')
    op.drop_column('technicians', 'status')
    op.drop_column('technicians', 'shift')
    op.drop_column('technicians', 'profile_image_url')
    op.drop_column('technicians', 'vehicle')
    op.drop_column('technicians', 'phone')
    op.drop_column('technicians', 'name')
    op.drop_column('technicians', 'lab_id')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_booking_id_fkey', 'reports', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.add_column('labs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('sample_collection_fee', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('platform_commission_pct', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'10'::double precision"), autoincrement=False, nullable=True))
    op.add_column('labs', sa.Column('license_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key('labs_owner_id_fkey', 'labs', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_labs_slug'), table_name='labs')
    op.drop_index(op.f('ix_labs_city'), table_name='labs')
    op.create_unique_constraint('labs_license_number_key', 'labs', ['license_number'])
    op.alter_column('labs', 'lng',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('labs', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('labs', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('labs', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('labs', 'is_active')
    op.drop_column('labs', 'commission_rate')
    op.drop_column('labs', 'plan')
    op.drop_column('labs', 'home_collection')
    op.drop_column('labs', 'is_iso')
    op.drop_column('labs', 'is_nabl')
    op.drop_column('labs', 'image_url')
    op.drop_column('labs', 'email')
    op.drop_column('labs', 'phone')
    op.drop_column('labs', 'slug')
    op.add_column('lab_tests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lab_tests', sa.Column('discount_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lab_tests', sa.Column('preparation', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('lab_tests', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('lab_tests', 'home_collection')
    op.drop_column('lab_tests', 'turnaround_hours')
    op.drop_column('lab_tests', 'mrp')
    op.alter_column('bookings', 'status',
               existing_type=sa.Enum('pending', 'confirmed', 'assigned', 'on_the_way', 'arrived', 'sample_collected', 'report_ready', 'completed', 'cancelled', name='bookingstatus'),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bookings', 'type',
               existing_type=sa.Enum('home_collection', 'lab_visit', name='bookingtype'),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_column('bookings', 'cancel_reason')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'discount_amount')
    op.drop_column('bookings', 'promo_code')
    op.drop_column('bookings', 'lng')
    op.drop_column('bookings', 'lat')
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'), autoincrement=False, nullable=True),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'critical', name='ticketpriority'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='support_tickets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='support_tickets_pkey')
    )
    # ### end Alembic commands ###
