"""Add razorpay_account_id to labs

Revision ID: 32cfd36c611e
Revises: 2a37937a8f16
Create Date: 2026-04-04 13:21:06.782432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '32cfd36c611e'
down_revision: Union[str, None] = '2a37937a8f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labs', sa.Column('razorpay_account_id', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('is_transferred', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('transfer_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'transfer_id')
    op.drop_column('payments', 'is_transferred')
    op.drop_column('labs', 'razorpay_account_id')
    # ### end Alembic commands ###
