"""add wallet_balance to user

Revision ID: 79f47924686f
Revises: 8fd8d4eb22bb
Create Date: 2026-04-05 15:40:27.347700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '79f47924686f'
down_revision: Union[str, None] = '8fd8d4eb22bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    # ### end Alembic commands ###
