"""Add HealthRecord model for user-uploaded vault items

Revision ID: b76c9dad45be
Revises: 79f47924686f
Create Date: 2026-04-05 15:57:22.210046

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b76c9dad45be"
down_revision: Union[str, None] = "79f47924686f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_records",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("file_path", sa.String(length=200), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("doctor_name", sa.String(length=100), nullable=True),
        sa.Column("hospital_name", sa.String(length=100), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("health_records")
    # ### end Alembic commands ###
