"""Add addresses array to user again

Revision ID: cbacde86fa29
Revises: 7cc697a3b703
Create Date: 2026-04-05 14:21:10.991344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cbacde86fa29'
down_revision: Union[str, None] = '7cc697a3b703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('addresses', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'addresses')
    # ### end Alembic commands ###
