"""add_city_to_technician

Revision ID: dac86d645b62
Revises: b76c9dad45be
Create Date: 2026-05-27 22:03:11.013224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'dac86d645b62'
down_revision: Union[str, None] = 'b76c9dad45be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'lab_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('lab_wallets', 'pending_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lab_wallets', 'total_earned',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lab_wallets', 'total_paid_out',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('reviews', sa.Column('booking_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'bookings', ['booking_id'], ['id'])
    op.add_column('technicians', sa.Column('city', sa.String(length=100), nullable=True))
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wallet_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('technicians', 'city')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'booking_id')
    op.alter_column('lab_wallets', 'total_paid_out',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lab_wallets', 'total_earned',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lab_wallets', 'pending_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'lab_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
